### ISSUE TITLE
`ensure_labels` sub command: To update/add labels as per conf to repo(s)

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#1]
### Read-me:
* As per discussion with @prashanthellina we have to implement a command line tool called `gitflow`
as a sub-command `ensure_labels` it will create the new labels as per our requirement and re-write the existing labels as well if required.
#### sample cmd"
```
gitflow ensure_labels --org "deepcompute" --repo "abc" --conf label.conf
```
#### Rules to follow:
* If a user specifies only:
--org - apply for all repo inside that organization.
--repo ("abc" (or) "deepcompute/abc") - apply label for only that repo.
--conf - configuration for creating labels
#### sample conf file look likes:
```
{"high-priority": {
    "name": ---,
    "color": ---,
    "description": ----,
    "akas": ["---", "----", ....],
  }
}
```

**Comment by prashanthellina** [comment]
@Rajendra-R 

1. `gitflow` -> `gitkanban`
1. `ensure_labels` -> `ensure-labels` (if basescript/argparse allows that)

**Comment by Rajendra-R** [comment]
### Status-update:
* Completed the `ensure_labels` feature.
### sample run cmd look like:
```
gitkanban -auth "d03bd15b410442e99e7da09022372442cc5e74" ensure-labels  --org "abc" --repo "testing" --config-file label.conf
```

**Comment by Rajendra-R** [comment]
### Status-update:
* Applied `ensure_labels` for all the repositories inside `deep-compute` organization.

**Comment by prashanthellina** [comment]
<img width="1027" alt="screenshot 2019-02-27 at 5 59 56 am" src="https://user-images.githubusercontent.com/3989/53485707-ef6be400-3a54-11e9-940b-5f75737983cb.png">

"in progress" label still present. this needs to be removed or people will end up using this along side the new label. @Rajendra-R

**Comment by Rajendra-R** [comment]
@prashanthellina 
* I think this has happened because fo `github server error` we didn't handle this exception properly so we got this problem.
![screenshot 2019-02-27 at 9 32 42 am](https://user-images.githubusercontent.com/16955073/53497791-fa357180-3a72-11e9-9899-2dffff8cb483.png)
* After re-ran that repo everything is fine.
![screenshot 2019-02-27 at 9 36 36 am](https://user-images.githubusercontent.com/16955073/53497907-3cf74980-3a73-11e9-8d52-eb691508ea50.png)

**Comment by Rajendra-R** [comment]
* This feature is done, so we can close this ticket.
