### ISSUE TITLE
Implement Travis Automation.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#12]
Have to implement an auto-deployment to Dockerhub for every release using travis.yml

**Comment by prashanthellina** [comment]
@Rajendra-R What is the effort estimate for this task?

**Comment by Rajendra-R** [comment]
* I think it is less than a day effort.

**Comment by Rajendra-R** [comment]
* Please ignore the above alerts It happened because of testing.

**Comment by Rajendra-R** [comment]
* We will work in this week.

**Comment by Rajendra-R** [comment]
* Started working on this issue.

**Comment by Rajendra-R** [comment]
* While testing we face some issues like in Travis we got an authorization error we are resolving that.

**Comment by Rajendra-R** [comment]
* Resolved all the issues in Travis It successfully deployed to Pypi and GitHub release.

**Comment by Rajendra-R** [comment]
* This issue is resolved so we can close this ticket.
