### ISSUE TITLE
Allow non .json extension for config file

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/gitkanban#134]
We should let the user an extension of their preference eg: .conf

**Comment by ColinKotar** [comment]
Starting to work on this now.

**Comment by ColinKotar** [comment]
Committed and published branch to await pull request.

**Comment by prashanthellina** [comment]
@ColinKotar Thank you. Please reference the relevant issue in the commit message. i.e. Instead "Removed .json extension check", you can do, "references #134, Removed .json extension check"

**Comment by prashanthellina** [comment]
@ColinKotar Go ahead and issue the pull request and mark @Rajendra-R  as the reviewer.

**Comment by ColinKotar** [comment]
Got it I'll fix it

**Comment by ColinKotar** [comment]
I have done all of the above, my branch is ready for merge.
