### ISSUE TITLE
Should not consider time during public holidays and off days.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#150]
* While calculating constraint we should not consider time during Public holidays and off days.
ex: If 3days constraint in between if we got public holidays or person off we should not consider time during those days.

**Comment by Rajendra-R** [comment]
* We will work on this issue next week.

**Comment by Rajendra-R** [comment]
* We will work this issue in this week.

**Comment by Rajendra-R** [comment]
* Will work this issue tomorrow.

**Comment by Rajendra-R** [comment]
* Started working on this feature.

**Comment by Rajendra-R** [comment]
* Working on this issue to satisfy all the possible cases like Public/personal/weekend holidays.

**Comment by Rajendra-R** [comment]
* The possible cases are listed given below.
- [ ] While calculating 6h constraint on the first day we got 3 hours for last comment and the next day is a public holiday and the coming day he took personal leave and then coming days were weekend then we have to consider Monday for remaining 3 hours.
- [ ] If a person took first-half day leave then we have to consider only second-half timing on that day for that person.
- [ ] For 3days constraint if a person took second-half leave then we have to consider 31/2 days.
etc..

**Comment by Rajendra-R** [comment]
@prashanthellina should we consider this issue for `snooze` timing also?

**Comment by prashanthellina** [comment]
@Rajendra-R No for now. Please track this is a new issue. We'll come back to it.

**Comment by Rajendra-R** [comment]
* Implemented the logic testing is in-progress.

**Comment by Rajendra-R** [comment]
* Testing is Done, giving PR

**Comment by Rajendra-R** [comment]
* This issue is resolved so we can close this ticket.
