### ISSUE TITLE
Bug: Alert refer to wrong issue.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#162]
* After implementing the new features while testing we are facing some issue like
1) Alert issue refers to wrong issues.
2) Inbox alerts are auto-resolved without any action.

**Comment by prashanthellina** [comment]
These seems like serious issues. Shouldn't this be in inprogress?

**Comment by Rajendra-R** [comment]
It should be, I thought after lunch will start work on this so will move when I start work on it.

**Comment by Rajendra-R** [comment]
* Started working on this issue.

**Comment by Rajendra-R** [comment]
* It is taking time to resolve the issue because it is taking time to replicate the problem in the testing environment, will resolve this soon.

**Comment by Rajendra-R** [comment]
* Working on other points of this issue.

**Comment by Rajendra-R** [comment]
* Testing is in-progress.

**Comment by Rajendra-R** [comment]
* This issue is solved so we can close this ticket.

**Comment by Rajendra-R** [comment]
* This issue is resolved so we can close this ticket.

**Comment by Rajendra-R** [comment]
* This issue is resolved so we can close this ticket.
