### ISSUE TITLE
Auto-resolve alerts in non working hours.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#180]
* Currently we are auto-resolving alerts if the person is in working hours, we need to modify that we can auto-resolve alerts if person not in working hours as well.

**Comment by Rajendra-R** [comment]
* This issue is already solved so we can close this ticket.

**Comment by prashanthellina** [comment]
@Rajendra-R How was it already solved it the issue happened for me today?

**Comment by Rajendra-R** [comment]
@prashanthellina For your case, this is not the reason later I realized by looking the code, There might be some other reason for the delay in auto-resolving the alert, by looking logs I didn't find the exact reason so I was thinking in different possible cases why it happened.
