### ISSUE TITLE
Send alerts to github.

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#5]
### Read-Me:
* As per discussion with prashanthellina we stop sending alerts to `pagerduty` instead of that send alerts to `github` because we are spending too much money to pagerduty for 6 users and we are not getting what we want.
* If we send to github we already paying for that and it meets some of our requirement like we can send alert to a particular person instead of repo_owners.

**Comment by Rajendra-R** [comment]
#### Status-update:
* As per discussion with @prashanthellina we implemented send alerts to github.
* This is how it looks like in `github` when an alert comes from `gitkanaban`.
![Screenshot 2019-03-14 at 12 26 02 PM](https://user-images.githubusercontent.com/16955073/54374014-9d31e200-4654-11e9-8e9c-ff4287eae0f5.png)

**Comment by prashanthellina** [comment]
- "Gitkanban:next-stale-issue-days-1-gitchecking/third#1" ==> "Gitkanban: next-stale-issue-days-1 failed for gitchecking/third#1"
- In description, Issue-url outside table not required as it is there inside the table
- In table, is the ordering of rows fixed?
- issue_url ==> Issue URL
- Issue URL should be the html URL
- queue_name ==> Queue
- constraint_name ==> Constraint
- person_name ==> Person
- repo_name ==> Repository
- alert_status - not required

**Comment by Rajendra-R** [comment]
Sure, will modify as per your suggestion.

**Comment by Rajendra-R** [comment]
#### Status-update
* Done the changes requested by prashanth
* Tested the gitkanban with different scenarios.
* Handled some of the exceptions in the code.
* Testing for deepcompute repos.

**Comment by Rajendra-R** [comment]
#### status-update:
* Testing for deepcompute repos is done.
* Have to deploy the `gitkanban` for deepcompute and nference.

**Comment by Rajendra-R** [comment]
* This feature is done so we are closing this ticket.
