### ISSUE TITLE
#Feature: Snooze 

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#51]
* No work will happen for two days in `in-progress`. I would like to move to "next" queue but worried that it will be forgotten in that queue. We would like it to automatically move to inprogress after two-day duration so people don't miss it. We need to think about how to support.

**Comment by Rajendra-R** [comment]
#### Status-update:
* As per discussion with @prashanthellina we came with an idea to implement this feature.
##### problem:
* When an issue is moving from `in-progress` to another any other queue because of other high priority issues, will forget about that issue for so many days. 
##### solution:
* Will create a new label like given below.
```
moveto-inprogress-1d
moveto-inprogress-2d
moveto-inprogress-3d
.....
moveto-inprogress-1w
moveto-inprogress-2w
.....
moveto-inprogress-1m
moveto-inprogress-2m
....
```
* When we are moving from `in-progress` to any other queue if you want to remind you then pick one of the right labels from the above and add to that issue before moving.
* Our `Gitkanban` will evaluate this constraint it will pick the issue of the above labels and check when was the label assigned will pick the time of that label and calculate the constraint and if it exceeds it will move back to `in-progress` again and remove the `moveto-inprogress...` label and assign `in-progress` label.
###### Note:
* To avoid more api calls store the label added time in the db and next time it ran if there is not action happend after that then will pick the time from db.

**Comment by Rajendra-R** [comment]
* We started working on this feature.

**Comment by Rajendra-R** [comment]
* We figured out the Github API for at what time the `label` was assigned for an issue at `event_url`.

**Comment by prashanthellina** [comment]
@Rajendra-R A nuance that needs to be taken care of --> If an issue was "snoozed" but before the time duration completed, let us say someone moves the issue to inprogress manually - We need to remove the snooze label automatically.

**Comment by Rajendra-R** [comment]
* We started working on this feature to-day will try to complete this by EOD.

**Comment by Rajendra-R** [comment]
* We pause this work for some time because we working on high priority work. once it is done will revert back to this.

**Comment by Rajendra-R** [comment]
* We are trying to figure out the Github API call with `event="labeled"` filtration with `label="moveto-inprogress-1d"`. to avoid more API calls.

**Comment by Rajendra-R** [comment]
* By looking in to the Github API documentation we can pass `parameters` for `issues/2/events` url.
refer: https://developer.github.com/v3/issues/events/#attributes
* But it is not working because they didn't provide that feature yet for `events`
refer: https://github.community/t5/GitHub-API-Development-and/Query-parameters-for-Issue-Events-v3/m-p/15067#M317

**Comment by Rajendra-R** [comment]
* As per discussion with @prashanthellina we have to implement this feature with a sub-command.
* Explained briefly how it works.
    1) when we run this sub-command it will pick all the issues related to our specific labels.
    2) Take one issue request the event URL from the last page check record by record to get the timestamp of the label was assigned.
    3) Evaluate the constraint if it is true to remove the `moveto-inprogress..` and respective queue label add `inprogress-status` label.
* Will configure this command after constraints had run.

**Comment by Rajendra-R** [comment]
* Implemented the logic
* Testing is in-progress.
* Figuring out the how to do Github API calls with multiple label filters because as per testing for some labels it is working and with some labels it is not working we need to test more about it to avoid more API calls.

**Comment by Rajendra-R** [comment]
@prashanthellina 
* I prefer these labels to be there for `snooze` feature so can you confirm it once?
```
"moveto-inprogress-2h",
"moveto-inprogress-4h",
"moveto-inprogress-6h",
"moveto-inprogress-1d",
"moveto-inprogress-2d",
"moveto-inprogress-3d",
"moveto-inprogress-4d",
"moveto-inprogress-5d"
```

**Comment by prashanthellina** [comment]
`moveto-inprogress-` prefix is good. Here are the suffixes I believe would be good

`1h`, `2h`, `4h`, `1d`, `2d`, `3d`, `1w`, `2w`, `1m` and
`eod`, `eow`, `eom` (end of day, week, month)
`tomorrow`, `next-week`, `next-month`

**Comment by Rajendra-R** [comment]
* Implementing the logic for all the labels which are mentioned above.

**Comment by Rajendra-R** [comment]
* This feature is done so we can close this ticket.
