### ISSUE TITLE
Support Escalation hierarchy for constraints

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#9]
##### Read-Me:
* In our `gitkanban` rules we have an `ownership_hierarchy` based on that if a person didn't respond after alerting him then we have to inform to the higher level people based on our hierarchy.

**ownership_hierarchy**
```
* system
* repo-group
* repo-group-label
* repo-group-queue
* repo-group-queue-label
* repo
* repo-label
* repo-queue
* repo-queue-label
* assignees
```

**Comment by Rajendra-R** [comment]
* As per discussion with Prashanthellina we designed a new constraint to support this feature.
![Screenshot 2019-03-20 at 3 22 31 PM](https://user-images.githubusercontent.com/16955073/54759810-35841580-4bc5-11e9-8ab0-e5914714facc.png)

**Comment by Rajendra-R** [comment]
#### status-update:
* Will be to start working on it to implement this feature.

**Comment by Rajendra-R** [comment]
#### Status-update:
* Logic implementation is in-progress. because we have some doubts will clarify with prashanth directly but not through a call and proceed further.

**Comment by Rajendra-R** [comment]
* Will try to complete this by EOD with testing.

**Comment by Rajendra-R** [comment]
@prashanthellina 
* While evaluating (time_duration) for escalation hierarchy in our constraints which person I have to consider either assignee or escalated ownership person?

**Comment by prashanthellina** [comment]
@Rajendra-R Can you elaborate?

**Comment by Rajendra-R** [comment]
* For example: if an issue contains assignee A and we raise an alert for that issue and he didn't respond so we will escalate to next level called `repo-queue-label` for that level B is the owner.
* So we added B to our alert issue assignees, still there is no update we will escalate to next level called `repo-queue` 
* To evaluate that constraint Which person I have to consider either A or B?

**Comment by prashanthellina** [comment]
Assignee: A
Level 1: B
Level 2: C

Assume A, B and C are in the same timezone and same work hours (9AM to 6PM)

Example:
Day 1, 11 PM -- Six hours since last update. However, can't alert A because work hours start at Day 2, 9 AM. Therefore, we send alert to A at Day 2, 9 AM
Day 2, 9 AM -- Raise alert to A
Day 2, 3 PM -- Six hours since previous alert was raised to A but issue not yet resolved. Escalate to B immediately because B's working hours are active.
Day 2, 9 PM -- Six hours since previous alert was raised to B but issue not yet resolved. However, can't alert C as work hours don't start till Day 3, 9AM
Day 3, 9 AM -- Raise alert to C

**Comment by Rajendra-R** [comment]
#### Status-update:
* Completed the logic for this feature.
* Tested the logic with below configuration.
```
    "ownership": [
        {
            "system_owner": ["rsrp30"]
        },
        {
            "repo": "deep-compute/gitkanban",
            "people": ["rsrp30"]
        },
        {
            "repo": "deep-compute/gitkanban",
            "queue": "in-progress",
            "label": "bug-type",
            "people": ["rsrp30"]
        }
    ],
    "constraints": [
                    {
                        "name": "inprogress-stale-hours-6",
                        "queue": "in-progress",
                        "time_since_activity": "1m",
                        "priority": "low",
                        "frequency": "hourly",
                        "continue": false,
                        "message": "No comment for an issue since 3 days",
                        "follow_ups": [
                            {
                                "time_elapsed": "2m",
                                "priority": "medium",
                                "message": "Do it now!"
                            },
                            {
                                "time_elapsed": "3m",
                                "priority": "medium",
                                "message": "Last chance before I escalate!"
                            },
                            {
                                "time_elapsed": "4m",
                                "priority": "high",
                                "message": "Please resolve now",
                                "escalate": true
                            }
                        ]
                    }
                ]
```
* As per configuration the output as given below.
![Screenshot 2019-03-25 at 1 27 53 AM](https://user-images.githubusercontent.com/16955073/54897322-4f13ae80-4e9e-11e9-8c15-f5eb484b140b.png)

**Comment by Rajendra-R** [comment]
### Status-update:
* Testing with different escalation hierarchies make sure it works fine.

**Comment by Rajendra-R** [comment]
* This feature implementation is done so we can close this ticket.

**Comment by prashanthellina** [comment]
Is it deployed in both setups @Rajendra-R ?
