### ISSUE TITLE
Should we consider timezone for snooze labels?

### ISSUE THREAD

**Issue by Rajendra-R** [deep-compute/gitkanban#97]
* As per discussion with @prashanthellina we came to know the state for which snooze labels we have to consider timezone and which are not.
* Should not consider timezone for the below labels.
```
"moveto-inprogress-1h", (1 Hour)
"moveto-inprogress-2h",
"moveto-inprogress-4h",
"moveto-inprogress-1d", (1 Day)
"moveto-inprogress-2d",
"moveto-inprogress-3d",
"moveto-inprogress-1w", (1 Week)
"moveto-inprogress-2w",
"moveto-inprogress-1m", (1 Month)
```
* Should consider timezone for these labels and prefer a person who assigned that label.
```
"moveto-inprogress-eod", (end of the day)
"moveto-inprogress-eow", (end of the week)
"moveto-inprogress-eom" (end of the month)
```

**Comment by Rajendra-R** [comment]
@prashanthellina 
* Where we have to do the separation of these labels either in the config file (or) in the code?
```
"moveto-inprogress-eod", (end of the day)
"moveto-inprogress-eow", (end of the week)
"moveto-inprogress-eom" (end of the month)
```

**Comment by prashanthellina** [comment]
@Rajendra-R If we have config like this we can differentiate

```json
{
    "snooze-labels": [
        {
            "name": "moveto-inprogress-1h",
            "time": "1h"
        },

        {
            "name": "moveto-inprogress-eod",
            "time": "eod"
        }
    ]
}
}
```

**Comment by Rajendra-R** [comment]
* We are replying the comments in the workplace regarding Gitkanban.

**Comment by Rajendra-R** [comment]
* We are working on the issues reported by the users so, it takes some time to come back for this issue.

**Comment by Rajendra-R** [comment]
* Because of high priority issue we pause this issue.

**Comment by Rajendra-R** [comment]
* Started working on this issue.

**Comment by Rajendra-R** [comment]
* This issue is done so we can close this ticket.
